# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a07dcc482fc60f45a4cc669a88438ea"
name = "2025-04-09-app-ui-project"
handle = "2025-04-09-app-ui-project"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

# [START build-admin-action.metafield-definition]
[product.metafields.app.issues]
type = "json"
name = "Issue Tracker"
description = "Tracks issues logged for this product"
access.admin = "merchant_read_write"
# [END build-admin-action.metafield-definition]

# [START build-admin-block.metafield-definition]
[product.metafields.app.issues]
type = "json"
name = "Issue Tracker"
description = "Tracks issues logged for this product"
access.admin = "merchant_read_write"
# [END build-admin-block.metafield-definition]
