# [START print-action-extension.configuration]
api_version = "2025-10"
[[extensions]]
name = "admin-print"
handle = "admin-print"
uid = "1c27ccfb-ebb2-96df-ec26-be0238fc10e2d8f8d8ec"
type = "ui_extension"


# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.jsx"
target = "admin.order-details.print-action.render"
# [END print-action-extension.configuration]

