api_version = "2025-10"
[[extensions]]
name = "t:name"
handle = "conditional-admin-action-extension"
uid = "3ca7f446-20fb-da23-6b62-b3c1e2852d2bfcf7472e"
type = "ui_extension"

# Only 1 target can be specified for each Admin action condition extension
[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-details.action.render"

# This is the relative path to the module that contains the logic to determine if the action trigger should be visible.
# [START conditional-action-extension.configuration]
[extensions.targeting.should_render]
module = "./src/condition/shouldRender.js"
# [END conditional-action-extension.configuration]

